# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Jun  3 12:21:01 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 451)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setEnabled(True)
        self.startButton.setGeometry(QtCore.QRect(10, 380, 114, 32))
        self.startButton.setObjectName("startButton")
        self.frequencyBox = QtGui.QGroupBox(self.centralwidget)
        self.frequencyBox.setGeometry(QtCore.QRect(10, 10, 221, 121))
        self.frequencyBox.setObjectName("frequencyBox")
        self.frequencyDisplay = QtGui.QLCDNumber(self.frequencyBox)
        self.frequencyDisplay.setGeometry(QtCore.QRect(10, 30, 201, 61))
        self.frequencyDisplay.setObjectName("frequencyDisplay")
        self.frequencySlider = QtGui.QSlider(self.frequencyBox)
        self.frequencySlider.setGeometry(QtCore.QRect(30, 90, 161, 21))
        self.frequencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.frequencySlider.setObjectName("frequencySlider")
        self.decrButton = QtGui.QPushButton(self.frequencyBox)
        self.decrButton.setGeometry(QtCore.QRect(10, 90, 20, 21))
        self.decrButton.setObjectName("decrButton")
        self.incrButton = QtGui.QPushButton(self.frequencyBox)
        self.incrButton.setGeometry(QtCore.QRect(190, 90, 21, 21))
        self.incrButton.setObjectName("incrButton")
        self.amplitudeBox = QtGui.QGroupBox(self.centralwidget)
        self.amplitudeBox.setGeometry(QtCore.QRect(10, 140, 221, 71))
        self.amplitudeBox.setObjectName("amplitudeBox")
        self.amplitudeSpinBox = QtGui.QDoubleSpinBox(self.amplitudeBox)
        self.amplitudeSpinBox.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.amplitudeSpinBox.setDecimals(3)
        self.amplitudeSpinBox.setMaximum(50.0)
        self.amplitudeSpinBox.setSingleStep(0.05)
        self.amplitudeSpinBox.setProperty("value", 1.0)
        self.amplitudeSpinBox.setObjectName("amplitudeSpinBox")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 210, 221, 91))
        self.groupBox.setObjectName("groupBox")
        self.saveLogButton = QtGui.QPushButton(self.groupBox)
        self.saveLogButton.setGeometry(QtCore.QRect(10, 50, 201, 32))
        self.saveLogButton.setObjectName("saveLogButton")
        self.clearDataButton = QtGui.QPushButton(self.groupBox)
        self.clearDataButton.setGeometry(QtCore.QRect(10, 20, 201, 32))
        self.clearDataButton.setObjectName("clearDataButton")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 300, 221, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.controlModeBox = QtGui.QComboBox(self.groupBox_2)
        self.controlModeBox.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.controlModeBox.setObjectName("controlModeBox")
        self.controlModeBox.addItem("")
        self.controlModeBox.addItem("")
        self.controlModeBox.addItem("")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 10, 231, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 211, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.timestampLabel = QtGui.QLabel(self.formLayoutWidget)
        self.timestampLabel.setObjectName("timestampLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.timestampLabel)
        self.timestampLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.timestampLineEdit.setEnabled(False)
        self.timestampLineEdit.setDragEnabled(False)
        self.timestampLineEdit.setObjectName("timestampLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.timestampLineEdit)
        self.positionLabel = QtGui.QLabel(self.formLayoutWidget)
        self.positionLabel.setObjectName("positionLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.positionLabel)
        self.positionLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.positionLineEdit.setEnabled(False)
        self.positionLineEdit.setObjectName("positionLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.positionLineEdit)
        self.currentLabel = QtGui.QLabel(self.formLayoutWidget)
        self.currentLabel.setObjectName("currentLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.currentLabel)
        self.currentLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.currentLineEdit.setEnabled(False)
        self.currentLineEdit.setObjectName("currentLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.currentLineEdit)
        self.accelerationLabel = QtGui.QLabel(self.formLayoutWidget)
        self.accelerationLabel.setObjectName("accelerationLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.accelerationLabel)
        self.accelerationLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.accelerationLineEdit.setEnabled(False)
        self.accelerationLineEdit.setObjectName("accelerationLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.accelerationLineEdit)
        self.commandLabel = QtGui.QLabel(self.formLayoutWidget)
        self.commandLabel.setObjectName("commandLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.commandLabel)
        self.commandLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.commandLineEdit.setEnabled(False)
        self.commandLineEdit.setObjectName("commandLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.commandLineEdit)
        self.cEffortLabel = QtGui.QLabel(self.formLayoutWidget)
        self.cEffortLabel.setObjectName("cEffortLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.cEffortLabel)
        self.cEffortLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.cEffortLineEdit.setEnabled(False)
        self.cEffortLineEdit.setObjectName("cEffortLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.cEffortLineEdit)
        self.dataOperations = QtGui.QGroupBox(self.centralwidget)
        self.dataOperations.setGeometry(QtCore.QRect(250, 250, 231, 121))
        self.dataOperations.setObjectName("dataOperations")
        self.zeroPosButton = QtGui.QPushButton(self.dataOperations)
        self.zeroPosButton.setGeometry(QtCore.QRect(10, 30, 221, 32))
        self.zeroPosButton.setObjectName("zeroPosButton")
        self.runRegressionButton = QtGui.QPushButton(self.dataOperations)
        self.runRegressionButton.setGeometry(QtCore.QRect(10, 60, 221, 32))
        self.runRegressionButton.setObjectName("runRegressionButton")
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(120, 380, 114, 32))
        self.stopButton.setObjectName("stopButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionDevice_Settings = QtGui.QAction(MainWindow)
        self.actionDevice_Settings.setObjectName("actionDevice_Settings")
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addAction(self.actionDevice_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.timestampLabel.setBuddy(self.timestampLineEdit)
        self.positionLabel.setBuddy(self.positionLineEdit)
        self.currentLabel.setBuddy(self.currentLineEdit)
        self.accelerationLabel.setBuddy(self.accelerationLineEdit)
        self.commandLabel.setBuddy(self.commandLineEdit)
        self.cEffortLabel.setBuddy(self.cEffortLineEdit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.frequencySlider, QtCore.SIGNAL("valueChanged(int)"), self.frequencyDisplay.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.startButton, self.stopButton)
        MainWindow.setTabOrder(self.stopButton, self.frequencySlider)
        MainWindow.setTabOrder(self.frequencySlider, self.amplitudeSpinBox)
        MainWindow.setTabOrder(self.amplitudeSpinBox, self.saveLogButton)
        MainWindow.setTabOrder(self.saveLogButton, self.controlModeBox)
        MainWindow.setTabOrder(self.controlModeBox, self.timestampLineEdit)
        MainWindow.setTabOrder(self.timestampLineEdit, self.positionLineEdit)
        MainWindow.setTabOrder(self.positionLineEdit, self.currentLineEdit)
        MainWindow.setTabOrder(self.currentLineEdit, self.accelerationLineEdit)
        MainWindow.setTabOrder(self.accelerationLineEdit, self.commandLineEdit)
        MainWindow.setTabOrder(self.commandLineEdit, self.cEffortLineEdit)
        MainWindow.setTabOrder(self.cEffortLineEdit, self.zeroPosButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.frequencyBox.setTitle(QtGui.QApplication.translate("MainWindow", "Indentor Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.decrButton.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.incrButton.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.amplitudeBox.setTitle(QtGui.QApplication.translate("MainWindow", "Amplitude", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.saveLogButton.setText(QtGui.QApplication.translate("MainWindow", "Save Log File", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDataButton.setText(QtGui.QApplication.translate("MainWindow", "Clear Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Control Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.controlModeBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.controlModeBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.controlModeBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Open Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Recieved Data", None, QtGui.QApplication.UnicodeUTF8))
        self.timestampLabel.setText(QtGui.QApplication.translate("MainWindow", "Timestamp", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.currentLabel.setText(QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.accelerationLabel.setText(QtGui.QApplication.translate("MainWindow", "Acceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLabel.setText(QtGui.QApplication.translate("MainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.cEffortLabel.setText(QtGui.QApplication.translate("MainWindow", "C Effort", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOperations.setTitle(QtGui.QApplication.translate("MainWindow", "Data Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroPosButton.setText(QtGui.QApplication.translate("MainWindow", "Zero Position Sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.runRegressionButton.setText(QtGui.QApplication.translate("MainWindow", "Run Linear Regression", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "App Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevice_Settings.setText(QtGui.QApplication.translate("MainWindow", "Device Settings", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

